spring:
  application:
    name: ticks-consumer-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

springdoc:
  swagger-ui:
    path: api-docs.html
logging:
  level:
    org.springframework: ERROR
    com.solactive: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

credentials:
  username: admin
  password: admin123
  role: ADMIN

jwt:
  secret-key: ticks-cosumer-service-key

export:
  service:
    uri: http://localhost:8081